### ISSUE TITLE
Typo GY521, see link

### ISSUE THREAD

**Issue by MoritzSMisko** [GuyCarver/MicroPython#2]
Hello there, while adapting your class to work on the rp2040, I found a small typo: 
'accel' class has no attribute 'setfulscaleaccelrange', should be 'setfullscaleaccelrange' see https://github.com/GuyCarver/MicroPython/blob/cb95afd55ee1f82cebeb5b648ef623e8ee0a2cf7/lib/GY521.py#L380

**Comment by MoritzSMisko** [comment]
Another Typo, there is no data6, but a _data6 https://github.com/GuyCarver/MicroPython/blob/cb95afd55ee1f82cebeb5b648ef623e8ee0a2cf7/lib/GY521.py#L534

**Comment by GuyCarver** [comment]
Thank you for the fixes.
